/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'community.lexicon.location.geo'

export { $nsid }

/** A physical location in the form of a WGS84 coordinate. */
type Main = {
  $type?: 'community.lexicon.location.geo'

  /**
   * The name of the location.
   */
  name?: string
  altitude?: string
  latitude: string
  longitude: string
}

export type { Main }

/** A physical location in the form of a WGS84 coordinate. */
const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    altitude: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    latitude: /*#__PURE__*/ l.string(),
    longitude: /*#__PURE__*/ l.string(),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
