/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as SifaDefs from '../defs.defs.js'
import * as LocationAddress from '../../../community/lexicon/location/address.defs.js'

const $nsid = 'id.sifa.profile.presentationDelivery'

export { $nsid }

/** Record representing a single occasion on which a presentation was delivered. This is the entry shown on a profile's activity timeline. At least one of presentationRef, title, or eventName is expected, enforced at the app layer. */
type Main = {
  $type: 'id.sifa.profile.presentationDelivery'

  /**
   * Calendar date of this delivery as YYYY-MM-DD (day only, no time). Future dates are allowed for upcoming deliveries. The day-only shape is enforced at the app layer. On the linked branch, derived from the event's startsAt in the event's own offset.
   */
  date?: string

  /**
   * Whether this delivery was in person, virtual, or hybrid. Stores the full community.lexicon.calendar.event mode token; absent means in person.
   */
  mode?:
    | 'community.lexicon.calendar.event#inperson'
    | 'community.lexicon.calendar.event#virtual'
    | 'community.lexicon.calendar.event#hybrid'
    | l.UnknownString

  /**
   * The presenter's role in this delivery. Open set; see id.sifa.defs#presentationRole.
   */
  role?:
    | 'id.sifa.defs#presenter'
    | 'id.sifa.defs#panelist'
    | 'id.sifa.defs#keynote'
    | 'id.sifa.defs#workshop'
    | 'id.sifa.defs#host'
    | l.UnknownString

  /**
   * Links specific to this delivery, such as the recording of this occasion.
   */
  links?: SifaDefs.PresentationLink[]

  /**
   * Fallback title for this delivery, used when no presentationRef is set.
   */
  title?: string

  /**
   * The same session as recorded on another person's profile. Set when you keep your own entry for work someone else has also recorded, so consumers can tell the two describe one thing rather than showing it twice. Each side stays its own record: the other person cannot edit yours, and yours does not change theirs. Resolve by AT-URI, since they will keep editing their copy.
   */
  sameAs?: SifaDefs.ExternalRecordRef

  /**
   * Scheduling status of this delivery, typically hydrated from a linked calendar event. Stores the full community.lexicon.calendar.event status token. Consumers should surface cancelled and postponed states.
   */
  status?:
    | 'community.lexicon.calendar.event#scheduled'
    | 'community.lexicon.calendar.event#cancelled'
    | 'community.lexicon.calendar.event#postponed'
    | 'community.lexicon.calendar.event#rescheduled'
    | 'community.lexicon.calendar.event#planned'
    | l.UnknownString

  /**
   * Structured delivery location. Sifa enforces ISO 3166-1 alpha-2 country codes at the app layer and surfaces country (for a flag) and locality (city); region, postalCode, and street are unused for deliveries. Takes precedence over the legacy location string when present.
   */
  address?: LocationAddress.Main

  /**
   * Optional reference to a community.lexicon.calendar.event for this occasion. Display fields are hydrated live from the target by AT-URI, with the stored fields as a fallback when the target is unavailable.
   */
  eventRef?: SifaDefs.ExternalRecordRef

  /**
   * Legacy free-text display location (city, country, or venue), retained for dual-read. Prefer the structured address field. On the linked branch, composed from the calendar event's structured locations.
   */
  location?: string

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString

  /**
   * Name of the event or venue. On the linked branch, hydrated from the calendar event's name.
   */
  eventName?: string

  /**
   * DIDs of co-speakers who presented alongside the author at this occasion. Any atproto account is allowed; hydrated to profile cards on read and linked to the co-speaker's Sifa profile.
   */
  coSpeakers?: l.DidString[]

  /**
   * Optional reference to the id.sifa.profile.presentation (the content) delivered here. When set, title, duration, and audiences are taken from it.
   */
  presentationRef?: SifaDefs.ExternalRecordRef
}

export type { Main }

/** Record representing a single occasion on which a presentation was delivered. This is the entry shown on a profile's activity timeline. At least one of presentationRef, title, or eventName is expected, enforced at the app layer. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    date: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 10 })),
    mode: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{
        knownValues: [
          'community.lexicon.calendar.event#inperson',
          'community.lexicon.calendar.event#virtual',
          'community.lexicon.calendar.event#hybrid',
        ]
      }>(),
    ),
    role: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{
        maxLength: 640
        knownValues: [
          'id.sifa.defs#presenter',
          'id.sifa.defs#panelist',
          'id.sifa.defs#keynote',
          'id.sifa.defs#workshop',
          'id.sifa.defs#host',
        ]
        maxGraphemes: 64
      }>({ maxLength: 640, maxGraphemes: 64 }),
    ),
    links: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<SifaDefs.PresentationLink>(
          (() => SifaDefs.presentationLink) as any,
        ),
        { maxLength: 20 },
      ),
    ),
    title: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 3000, maxGraphemes: 300 }),
    ),
    sameAs: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<SifaDefs.ExternalRecordRef>(
        (() => SifaDefs.externalRecordRef) as any,
      ),
    ),
    status: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{
        knownValues: [
          'community.lexicon.calendar.event#scheduled',
          'community.lexicon.calendar.event#cancelled',
          'community.lexicon.calendar.event#postponed',
          'community.lexicon.calendar.event#rescheduled',
          'community.lexicon.calendar.event#planned',
        ]
      }>(),
    ),
    address: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<LocationAddress.Main>(
        (() => LocationAddress.main) as any,
      ),
    ),
    eventRef: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<SifaDefs.ExternalRecordRef>(
        (() => SifaDefs.externalRecordRef) as any,
      ),
    ),
    location: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 2560, maxGraphemes: 256 }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    eventName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 3000, maxGraphemes: 300 }),
    ),
    coSpeakers: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'did' }), {
        maxLength: 20,
      }),
    ),
    presentationRef: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<SifaDefs.ExternalRecordRef>(
        (() => SifaDefs.externalRecordRef) as any,
      ),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
