/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as SifaDefs from '../defs.defs.js'

const $nsid = 'id.sifa.profile.presentation'

export { $nsid }

/** Record representing a single reusable presentation (the content), distinct from the occasions on which it is delivered. */
type Main = {
  $type: 'id.sifa.profile.presentation'

  /**
   * Canonical links for this content, such as slides or a recording.
   */
  links?: SifaDefs.PresentationLink[]

  /**
   * Title of the presentation.
   */
  title: string

  /**
   * Typical length of the presentation, a fixed value or a range, in minutes.
   */
  duration?: Duration

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString

  /**
   * Optional cover image for the presentation. Rendered as the talk-page hero and OpenGraph image. Max 2 MB, PNG, JPEG, or WebP.
   */
  coverImage?: l.BlobRef

  /**
   * Optional reference to a long-form write-up of this presentation (a pub.leaflet.document or site.standard.document holding video, transcript, or article).
   */
  writeupRef?: SifaDefs.ExternalRecordRef

  /**
   * Description or abstract of the presentation.
   */
  description?: string

  /**
   * Intended audiences for this presentation, open text (e.g. 'Engineering leaders', 'Beginners').
   */
  intendedAudiences?: string[]
}

export type { Main }

/** Record representing a single reusable presentation (the content), distinct from the occasions on which it is delivered. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    links: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<SifaDefs.PresentationLink>(
          (() => SifaDefs.presentationLink) as any,
        ),
        { maxLength: 20 },
      ),
    ),
    title: /*#__PURE__*/ l.string({
      maxLength: 3000,
      minLength: 1,
      maxGraphemes: 300,
    }),
    duration: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Duration>((() => duration) as any),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    coverImage: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({
        accept: ['image/png', 'image/jpeg', 'image/webp'],
        maxSize: 2000000,
      }),
    ),
    writeupRef: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<SifaDefs.ExternalRecordRef>(
        (() => SifaDefs.externalRecordRef) as any,
      ),
    ),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 50000, maxGraphemes: 5000 }),
    ),
    intendedAudiences: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.string({ maxLength: 1000, maxGraphemes: 100 }),
        { maxLength: 20 },
      ),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A presentation length in minutes: a fixed value (minMinutes only) or a range (minMinutes to maxMinutes). */
type Duration = {
  $type?: 'id.sifa.profile.presentation#duration'

  /**
   * Upper bound in minutes when the length is offered as a range. Omit for a fixed length.
   */
  maxMinutes?: number

  /**
   * Length in minutes, or the lower bound when the length is offered as a range.
   */
  minMinutes: number
}

export type { Duration }

/** A presentation length in minutes: a fixed value (minMinutes only) or a range (minMinutes to maxMinutes). */
const duration = /*#__PURE__*/ l.typedObject<Duration>(
  $nsid,
  'duration',
  /*#__PURE__*/ l.object({
    maxMinutes: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer({ minimum: 1 }),
    ),
    minMinutes: /*#__PURE__*/ l.integer({ minimum: 1 }),
  }),
)

export { duration }
